# Generated by Django 4.0.5 on 2023-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0003_alter_prestamo_fecha_alter_prestamo_fechadev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.CharField(max_length=15, verbose_name='Fecha de prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechadev',
            field=models.CharField(max_length=15, verbose_name='Fecha de devolucion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaposdev',
            field=models.CharField(max_length=15, verbose_name='Fecha posible de devolucion'),
        ),
    ]
